### ISSUE TITLE
Unpaired electrons as input parameters in ase calculator

### ISSUE THREAD

**Issue by Dnasiul** [grimme-lab/xtb-python#47] opened 2021-02-11 21:37 UTC
Hello,

In the standalone version of xtb you can define a file, .UHF, containing the number of unpaired electrons. Is it possible for the xtb-python to read that file? Would it be possible to include the number of unpaired electrons as additional input parameter for the ase calculator?

**Comment by awvwgk** [comment] 2021-02-11 21:45
Duplicate of https://github.com/grimme-lab/xtb-python/issues/42

**Comment by Dnasiul** [comment] 2021-02-11 23:15
Got it, Thanks!

So, it would be like this:

```
uhf = n # number of unpaired electrons
imm = np.zeros(len(atoms))
imm[-uhf:] = 1
atoms.set_initial_magnetic_moments(imm)
print('UHF =', int(atoms.get_initial_magnetic_moments().sum().round()))
```

**Closed** 2021-05-04 11:35 UTC
Labels: ase, duplicate
