### ISSUE TITLE
wanna get a function of optimization 

### ISSUE THREAD

**Issue by sym823808458** [grimme-lab/xtb-python#54] opened 2021-07-13 07:59 UTC
### Is your feature request related to a problem? Please describe.
In API documentation, there is only single point calculation method. It is really helpful if the python_xtb could contain the function of opimization class.

**Comment by awvwgk** [comment] 2022-07-03 19:46
Upstream issue https://github.com/grimme-lab/xtb/issues/403 needs to be resolved first.

**Comment by TyBalduf** [comment] 2022-10-14 00:55
Closing this out as a duplicate of https://github.com/grimme-lab/xtb-python/issues/38

**Closed** 2022-10-14 00:55 UTC
Labels: enhancement, xtb
