### ISSUE TITLE
Cannot load libmkl_avx512.so or libmkl_def.so

### ISSUE THREAD

**Issue by Dnasiul** [grimme-lab/xtb-python#75] opened 2022-05-20 03:15 UTC
### Describe the bug

Hi,

I am getting

Intel MKL FATAL ERROR: Cannot load libmkl_avx512.so or libmkl_def.so 

when I try to run a python script which imports xtb-python compiled with parent xtb-6.5.0

### To Reproduce

Bash script to compile_and_install_xtb-python.sh:

```
#!/bin/bash

# Get standalone package

wget https://github.com/grimme-lab/xtb/releases/download/v$1/xtb-$1-linux-x86_64.tar.xz
tar xf xtb-$1-linux-x86_64.tar.xz
cd xtb-$1

# Edit first line on lib/pkgconfig/xtb.pc:

sed -i 's|prefix=\/|prefix='$PWD'|g' lib/pkgconfig/xtb.pc

# Define environment variables:

export PKG_CONFIG_PATH=$PWD/lib/pkgconfig

# Get and compile xtb-python:

git clone https://github.com/grimme-lab/xtb-python python
cd python

meson setup build --prefix=$PWD --default-library=shared

ninja -C build install

# Install to site-packages:

python3.8 -m pip install -e .
```

To install 6.5.0: `./compile_and_install_xtb-python.sh 6.5.0`
(likewise for 6.4.1)

The test python script is the following (run.py):

```
from ase.io import read
from xtb.ase.calculator import XTB
atoms = read('H2CO.xyz')
atoms.calc = XTB(method="GFN2-xTB")
energy = atoms.get_potential_energy()
print(energy)
```

With xtb-6.4.1:

1. `./compile_and_install_xtb-python.sh 6.4.1`
2. `python3.8 run.py`
3. Output: `-195.25932038970979`

With xtb-6.5.0:

1. `./compile_and_install_xtb-python.sh 6.5.0`
2. `python3.8 run.py`
3. Output: `Intel MKL FATAL ERROR: Cannot load libmkl_avx512.so or libmkl_def.so.`

### Expected behaviour

As shown before for xtb-6.4.1

I would appreciate any light on the subject.

### Files

[xtb-python-test.zip](https://github.com/grimme-lab/xtb-python/files/8735643/xtb-python-test.zip)

**Comment by Dnasiul** [comment] 2022-05-20 03:27
By the way, [this workaround](https://community.intel.com/t5/Intel-oneAPI-Math-Kernel-Library/mkl-fails-to-load/m-p/1155538) (export LD_PRELOAD) does the trick for xtb-6.5.0, but I wouldn't consider it as an ideal definitive solution.

**Comment by awvwgk** [comment] 2022-05-20 06:04
To dynamically load a shared library linked against the MKL the `mkl_rt` library must be linked, either by `LDPRELOAD` or by building the `xtb` shared library using `-Dla_backend=mkl-rt`. With MKL this is unfortunately the only available solution provided by Intel.

**Comment by awvwgk** [comment] 2022-05-23 09:04
Since this is the expected behavior of MKL linking, I'm closing this issue as resolved.

**Closed by awvwgk** 2022-05-23 09:04 UTC
Labels: build

**Comment by Dnasiul** [comment] 2022-05-23 15:42
Thanks!
